spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hbm?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update #(create, create-drop, update)
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: INFO
    org:
      ostenant:
        springboot:
          learning:
            examples: DEBUG
